### PR TITLE
Add website to DESCRIPTION + improve look

### PR DESCRIPTION
**Pull request by olivroy**
* USe pkgdown bootstrap 5 adds a search bar, which is handy.
* I used the logo as the primary color for the website!

### CODE REVIEW

**Comment by mayer79** [comment]
Hi, and thanks for your improvement. Should we put the _pkgdown.yml into a pkgdown folder?

**Comment by olivroy** [comment]
It is up to you. pkgdown recognizes both locations!

**Comment by mayer79** [comment]
Looks very shiny, thanks a lot :-)

**Comment by olivroy** [comment]
Glad you like it!

**Pull request merged**
