### PR TITLE
Updating error to explicitly flag/allow tibble

### PR DESCRIPTION
**Pull request by pdwaggoner**
Suggesting: `"'data' should be a tibble or data.frame!" = is_tibble(data), ` in error message, in line with current syntax in this function. Same spirit as PR #34 .

### CODE REVIEW

**Comment by mayer79** [comment]
Hello and thanks for digging into the code! Currently, there is no plan to add new dependencies to `missRanger`. Thus, I will keep your PR in the backlog in case this plan changes.

**Comment by pdwaggoner** [comment]
Cool, thanks. We can easily add as a `suggest`, or quietly suggest locally in the function call, e.g., 

```{r}
if (!requireNamespace("tibble", quietly = TRUE)) {
    stop("Package \"tibble\" needed for this function to work. Please install it.",
         call. = FALSE)
  }
```

Certainly no worries if you'd rather not include the change still. Just some thoughts from me. But either way, it's such a great package. Thanks for it!

**Comment by mayer79** [comment]
Thanks for the snippet. Since a `tibble` is a `data.frame`, I think the current checks are acceptable, although your suggestions make definitively sense and I might consider them at a later time point.

**Comment by pdwaggoner** [comment]
Cool, thanks for considering.

**Pull request closed without merging**
